version: "3"

services:
  drand-client-1:
    container_name: testdrng-drand_0
    image: angelocapossele/drand:1.1.3
    entrypoint: /data/client-script.sh
    networks:
      - drandnetwork
    ports:
      - "8000:8000/tcp"
      - "8800:8081/tcp"
    environment:
      LEADER: 1
      GOSHIMMER: "127.0.0.1:8080"
  drand-client-2:
    container_name: drand2
    image: angelocapossele/drand:1.1.3
    entrypoint: /data/client-script.sh
    networks:
      - drandnetwork
    ports:
      - "8001:8000/tcp"
      - "8801:8081/tcp"
    environment:
      GOSHIMMER: "127.0.0.1:8080"
  drand-client-3:
    container_name: drand3
    image: angelocapossele/drand:1.1.3
    entrypoint: /data/client-script.sh
    networks:
      - drandnetwork
    ports:
      - "8002:8000/tcp"
      - "8802:8081/tcp"
    environment:
      GOSHIMMER: "127.0.0.1:8080"
  drand-client-4:
    container_name: drand4
    image: angelocapossele/drand:1.1.3
    entrypoint: /data/client-script.sh
    networks:
      - drandnetwork
    ports:
      - "8003:8000/tcp"
      - "8803:8081/tcp"
    environment:
      GOSHIMMER: "127.0.0.1:8080"
  drand-client-5:
    container_name: drand5
    image: angelocapossele/drand:1.1.3
    entrypoint: /data/client-script.sh
    networks:
      - drandnetwork
    ports:
      - "8004:8000/tcp"
      - "8804:8081/tcp"
    environment:
      GOSHIMMER: "127.0.0.1:8080"

networks:
  drandnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.222.0/24
